const actionTypes = {
  ANONYMOUS: 'ANONYMOUS',
  LOGGED_IN: 'LOGGED_IN',
  LOGGED_OUT: 'LOGGED_OUT',
  GET_USER_ID: 'GET_USER_ID',
  AUTH_ERROR: 'AUTH_ERROR',
  FETCH_USER: 'FETCH_USER',
  FETCH_OLD_STATS: 'FETCH_OLD_STATS',
  THIS_USER: 'THIS_USER',
};

export default actionTypes;
